name: PR Initial Comment

on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  comment_pr:
    name: Comment Initial PR
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Comment on PR
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            var fs = require('fs');
            var data = fs.readFileSync('.github/workflows/template.md', {encoding:'utf8', flag:'r'});
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `${data}`
            })